### ISSUE TITLE
Single deployment needs a default/generic ingress controller

### ISSUE THREAD

**Issue by jeffgrunewald** [Datastillery/charts#20]
In order to provide fine-grained control of routing to web-based services provided by the platform within the cluster and to adequately present a prod-like environment for local development or enable future deployment to a self-hosted on-prem data center, a default ingress controller that is not specific to any one cloud provider should be included in the chart to deploy all of the platform services.
The primary/officially supported controller that is also cloud agnostic still appears to be Nginx at this time.

**Comment by jdenen** [comment]
> In order to provide fine-grained control of routing to web-based services provided by the platform within the cluster and to adequately present a prod-like environment for local development

To make routing work locally like it does in a production Kubernetes environment

> or enable future deployment to a self-hosted on-prem data center,

or make on-prem possible,

> a default ingress controller that is not specific to any one cloud provider should be included in the chart to deploy all of the platform services.

we need a default ingress controller that's not specific to a cloud provider.

> The primary/officially supported controller that is also cloud agnostic still appears to be Nginx at this time.

It's probably Nginx.

**Comment by jdenen** [comment]
❤️@jeffgrunewald
