### ISSUE TITLE
Add Vault to Master Chart

### ISSUE THREAD

**Issue by ksmith-accenture** [Datastillery/charts#260]
# What?

Add Vault to the Master Helm Chart.  The Vault addition should:

- [ ] Be able to be feature toggled via configuration
- [ ] Inject the connection values into the rest of the stack
- [ ] Expose its configurations to the user
- [ ] Deploy in the same namespace as the rest of the stack

# Why?

In order for the data platform to interact with Auth0 and AWS it must fetch credentials from Vault.  Bringing Vault into the Master Helm Chart allows for smoother integration and reduces deployment overhead

**Comment by bmitchinson** [comment]
Notes as we work on this ticket:
---

### Things to do:
- [ ] satefulset.yaml has another dev mode conditional
  - Should we get rid of all the dev mode stuff and just have a more consistent setup?

### Questions
