### ISSUE TITLE
Add Monitoring Stack to Master Chart

### ISSUE THREAD

**Issue by ksmith-accenture** [Datastillery/charts#262]
# What?

Add the monitoring stack to the Master Helm Chart.  The monitoring addition should:

- [ ] Be able to be feature toggled via configuration
- [ ] Inject the connection values into the rest of the stack
- [ ] Expose its configurations to the user
- [ ] Deploy in the same namespace as the rest of the stack

Parts of the monitoring stack:

- [ ] Prometheus
- [ ] Grafana
- [ ] Kube State Metrics
- [ ] Node Exporter
- [ ] Alert Manager
- [ ] Push Gateway

# Why?

The monitoring stack provides insight to the status and health of the data platform pipeline.   Bringing monitoring into the Master Helm Chart allows for smoother integration and reduces deployment overhead

**Comment by LtChae** [comment]
Consider using the public prometheus/grafana charts
https://github.com/grafana/helm-charts/tree/main/charts/grafana
https://github.com/prometheus-community/helm-charts

**Comment by bmitchinson** [comment]
Qs:

- Why is prometheus failing the readiness check. no logs on it failing, we just see the event?
- Is there a way to continue doing handlebars templating through the dataset alerts (currently alerts.yaml in `monitoring`, in the deploy repo? For now we’re leaving them out since they shouldn't be in the public chart

**Comment by bmitchinson** [comment]
Created https://github.com/Datastillery/internal/issues/88 to track fixing the "EKS Web Application Firewall" dashboard, as it's currently broken on prod.

**Comment by bmitchinson** [comment]
Created a readme for how dashboards should be updated / published https://github.com/SmartColumbusOS/scosopedia/wiki/Publishing-and-Maintaining-Grafana-Dashboards
