### ISSUE TITLE
Migrate Auth0 Keys to Kubernetes Secrets from Vault

### ISSUE THREAD

**Issue by ksmith-accenture** [Datastillery/charts#269]
# What?

Services require Auth0 keys in order to authenticate users against Auth0, these credentials should be moved from Vault to Kubernetes secrets configurable at deploy time.  The following services need their Auth0 keys moved to Kubernetes secrets:

- [ ] ~~Discovery API~~ **NOTE: Discovery API did not use Auth0 Keys and has been removed from this card.**
- [x] Andi
- [x] Andi Public

## Outstanding Questions for Entry:
- Does the master chart need to be updated in order to use Kubernetes secrets in Andi/Discovery API? Or can we just add the secrets directly to Kubernetes Secrets and then update the code in ANDI/Discovery API?
- Are we adding the ability to add the secret to Kubernetes Secrets programmatically? 
- Where/When will this change be deployed? 
- In the charts repo, there is a secrets.yml file in both ANDI and discovery API. It seems to hold secrets in the format of a Kubernetes secret. Then, it seems as though the deployment.yml file uses those values. Then, it seems as though the ANDI/Discovery API code uses the get_env_variable to retrieve the value. Is this the correct understanding?

## Steps to complete the card
1. Research Kubernetes Secrets and determine how to add a secret.  
2. Add the secrets for Auth0 to Kubernetes Secrets.
3. Update the SecretsService in Andi to use Kubernetes Secrets instead of Vault. 
4. Update the SecretsService in Discovery API to use Kubernetes Secrets instead of Vault.

# Why?

Deploying a new instance of the UrbanOS data hub with the helm chart does not populate these essential credentials into vault.  Once the data hub is deployed a user will have to manually inject the credentials into vault which is tedious and poorly documented.  These secrets would be more appropriately stored in Kubernetes secrets to enable the deployments to function immediately upon initial deployment.

**Comment by bmitchinson** [comment]
From Refinement 6/9

Minio is already in use in the integration tests as an S3 stand-in.

There could be small issues in replacing it, since so many areas of the OS utilize s3. Will need to confirm each area functions as intended.

**Comment by srashee1** [comment]
andi-public isn't accessible in dev

**Comment by srashee1** [comment]
discovery isn't accessible in staging
