### ISSUE TITLE
Forklift should no longer be a statefulset

### ISSUE THREAD

**Issue by jeffgrunewald** [Datastillery/charts#49]
Forklift no longer requires a persistent storage connection or network identity based on relatively old refactors as of this writing.

Having it implemented as a statefulset instead of a deployment adds overhead and makes deployments unnecessarily difficult. It also makes unnecessarily difficult to horizontally scale the forklift service for concurrency.

**Comment by ksmith-accenture** [comment]
Forklift is a Deployment at the time of this comment
